### ISSUE TITLE
Add a ForbiddenFunctionsSniff

### ISSUE THREAD

**Issue by richan-fongdasen** [suitmedia/php-code-standards#2]
These are the forbidden functions i suggested so far : 
- `die()`
- `exit()`
- `dd()`
- `phpinfo()`
- `eval()`
- `assert()`

Feel free to discuss about this...

Poke @feryardiant @wicochandra

**Comment by feryardiant** [comment]
**AFAIK** `die()`, `exit()` & `eval()` are already available on [PHPMD 0.2](https://phpmd.org/rules/design.html)

We could use 

``` xml
<rule ref="Squiz.PHP.NonExecutableCode"/>
```

for `die()` and `exit()` but dunno for `eval()` _yet_

**Updated**: sorry typo :grimacing:

**Comment by feryardiant** [comment]
``` xml
<rule ref="Squiz.PHP.Eval"/>
```

for `eval()`

**Comment by feryardiant** [comment]
We already have both [`Squiz.PHP.NonExecutableCode`](https://github.com/suitmedia/php-code-standards/blob/master/Suitmedia/ruleset.xml#L39) and [`Squiz.PHP.Eval`](https://github.com/suitmedia/php-code-standards/blob/master/Suitmedia/ruleset.xml#L36) anyway :dizzy_face:

**Comment by richan-fongdasen** [comment]
Actually, Squiz.PHP.NonExecutableCode will only generate warning messages for every line of codes that would never be executed. For example : 

``` php
class Foo
{
    private $personName;

    public function greet($yourName)
    {
        return $yourName . ', boo!!';
        // This line would never be executed on any conditions!
        $this->personName = $yourName;
    }
}
```

But the purpose of this issue is to completely forbid the usage of previously given functions.

**Comment by feryardiant** [comment]
+1
